### PR TITLE
building compression: add compounding energy / cost multiplier option

### PR DESCRIPTION
**Pull request by SurvivorBob**
Presently the energy and cost multiplier add a fixed barrier for going
from normal buildings to compressed ones, but afterwards there are few
reasons not to immediately build the highest tier of machinery given
enough power generation and production of such machines.

To allow players to address this at their option, this change adds the
following features:

* Adds a boolean setting that, when toggled, turns the fixed multiplier
  into a compounding multiplier. That is, instead of all compressed
  machines being M times more costly than an equivalent collection of
  non-compressed machines, a compressed machine is instead M times more
  costly than an equivalent collection of machines 1 tier lower. This
  allows players the option of having higher-tier machines be less
  power-efficient in exchange for the space savings provided, adding an
  element of choice as to which tier to build in a given situation.
* Changes the energy and cost multiplier settings for compressed
  buildings from a fixed-choice integer to a user-input double. This
  allows for multipliers like 1.4142 (square root of 2) to be
  specified (which would compound to 2 over 2 tiers, and to 4 over 4
  tiers).
* Adds English-language localization for the added and changed
  settings.

Note the following limitations:

* When non-integer multipliers are specified for build costs, the
  resulting costs are rounded up to the next unit, because we can't
  have fractional items.

### CODE REVIEW

**Review by oorzkws — APPROVED** [review]
I think I have some better wording here, but I would like some feedback. Overall, I approve the changes.

**Comment by Cereal-Sam** [comment]
Sorry for the late reply and thanks for the PR!
To add up to the comments by @oorzkws , we do not want default values or range limits of settings in the locale files.
Examples are fine, but adding those numbers would mean that the locale file of each language requires a change in case those numbers change. Apart from that, those numbers are displayed in factorio now when hovering above the setting/the input GUI.

**Comment by SurvivorBob** [comment]
Thanks for the remarks and revisions. I've updated the locale file to take feedback from @oorzkws and @Cereal-Sam into account.

Sounds like we need a backlog task to remove existing range limits in locale files (e.g. `omnicompression_building_levels`) if omitting them is the present-day consensus.

**Comment by Cereal-Sam** [comment]
Good point, i did not notice that omnicompression_building_levels and omnicompression_multiplier already have the range specified in the locale.
You can remove that if you want, otherwise I will do it after merging this to avoid conflicts.

**Comment by SurvivorBob** [comment]
To me those would make sense separately from this PR (seems outside its scope).

**Pull request merged**
